Repository elchininet/isometric, pull requests merged in 2024-12, with the labels that each got.

#218 Replace some logical OR by nullish coalescing operators
  src/@classes/abstract/IsometricDraggableAbstract/IsometricDraggableAbstract.ts
  src/@classes/abstract/IsometricStarPolygonAbstract/IsometricStarPolygonAbstract.ts
  src/@classes/public/IsometricCircle/IsometricCircle.ts
  src/@classes/public/IsometricRectangle/IsometricRectangle.ts
Labels: bug

#217 Add support for classes to isometric objects.
  README.md
  dist/web/isometric.js
  src/@classes/abstract/IsometricGraphicAbstract/IsometricGraphicAbstract.ts
  src/@classes/abstract/IsometricGraphicAbstract/types.ts
  tests/__snapshots__/snapshots.test.ts.snap
  tests/properties.test.ts
  tests/snapshots.test.ts
Labels: enhancement

#219 Small changes in the documentation
  README.md
  src/@classes/abstract/IsometricGraphicAbstract/IsometricGraphicAbstract.ts
Labels: documentation
